name: local_case
description: A Flutter package for localized text case conversion and number-to-words transformation, supporting multiple languages including French, Spanish, Czech, German, and Turkish.
version: 0.0.2
license: MIT
homepage: https://github.com/ulusoyomer/Local-Case
repository: https://github.com/ulusoyomer/Local-Case

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
